
Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'app/views/**/*'
    - 'db/schema.rb'

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - 'db/seeds.rb'
    - 'config/environments/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
