language: ruby
rvm:
  2.4.0

before_script:
  - cp config/database.yml.example config/database.yml
  - psql -c 'create database school_area_api_test;' -U postgres
  - RAILS_ENV=test rake db:schema:load
  - bundle install

rspec:
  script:
    - bundle exec rspec
